let x=100;
console.log(typeof(x));
let y=12.34;
console.log(typeof(y));
let z="Abc";
console.log(typeof(z));
let i=true;
console.log(typeof(i));
let j;
console.log(typeof(j));
let obj=new Date();
console.log(typeof(obj));