var a="10";
var b="20";
console.log(b/a);
console.log("10"/"2");
console.log(Number(a)+Number(b));
console.log(+a + +b);
let c="30";
console.log(typeof(c));
c=Number(c);
console.log(typeof(c));
let i=10;
console.log(typeof(i));
i=String(i);
console.log(typeof(i));
let k="true";
k=Boolean(k);
console.log(typeof(k));
console.log(Boolean("abc"));
console.log(Boolean(null));
console.log(Boolean(0));
console.log(Boolean(1));